### ISSUE TITLE
Package in the official moodle plugin repository

### ISSUE THREAD

**Issue by nmarafo** [trampgeek/moodle-filter_ace_inline#13]
Hello and congratulations for this great plugin. The filter will be incorporated into the official Moodle repository? I have installed it in my Moodle and it works perfectly...

**Comment by fastsandslash** [comment]
It is currently in the process of being submitted; awaiting https://tracker.moodle.org/browse/MDL-77000 error with MarkdownExtra functionality. Major updates and extra functionality from the development branch will be merged through soon, and this works with the current development branch of CodeRunner.

**Comment by fastsandslash** [comment]
Now in official Moodle Repository. :-)
