### ISSUE TITLE
Quick precheck if the filter should be skipped

### ISSUE THREAD

**Issue by mudrd8mz** [trampgeek/moodle-filter_ace_inline#20]
It is a good practice to make a quick performance-cheap check for the given {{$text}} in order to decide whether the filter should even attempt to do its job (which may be quite expensive, involve regular expressions etc).

in this case I think there can be a quick {{strpos()}} check searching for something like {{data-ace-}} around https://github.com/trampgeek/moodle-filter_ace_inline/blob/e3c0f1a8b14d5ee3628415cf53bc05d14151cc20/filter.php#L56

See for example how some core filters do it - e.g. https://github.com/moodle/moodle/blob/f7a8df253b0ff3fc8ad73135b645d4e9317b06cb/filter/mediaplugin/filter.php#L72

**Comment by fastsandslash** [comment]
Hi, David.

Apologies, but after the config is set, and when the call to the "do_ace_highlight"/"do_ace_interactive" function is called, there is a text-check to see if one should filter, if the keywords of "ace-highlight-code" etc. are on the page. This was implemented to avoid unnecessary running of the filter.

An example of this for the "do_ace_highlight" is here; and there is one for the interactive proportion as well.

https://github.com/trampgeek/moodle-filter_ace_inline/blob/e3c0f1a8b14d5ee3628415cf53bc05d14151cc20/filter.php#L78-L81

Is this what you were referencing?

Thanks,

Michelle

**Comment by mudrd8mz** [comment]
Oh yes indeed there it is! I'm so sorry - I missed it! All good - and well done!
