### ISSUE TITLE
The Button label setting does not have any affect 

### ISSUE THREAD

**Issue by lassikor** [trampgeek/moodle-filter_ace_inline#21]
Hi,
we have been testing this filter now a while and it seems to work quite nicely. However, we haven't found any way to change the default "Try it!" text within the button site wide. The administrator's setting "Button label" does not change the text and nothing happens if the text is changed directly to the string file. I suppose that the JavaScript code sets the text but somehow does not obey the Moodle setting. The dark mode setting seems to work properly. We have the newest plugin version (1.3.1) and Moodle 4.1. We tested this also in Moodle 3.9 .
An user can change the text by using data-button-name parameter but it would be nice if the default text could be set as well. 

BR Lassi Korhonen
University of Oulu

**Comment by fastsandslash** [comment]
Thank you for reporting this bug; it will be fixed in the next version release.

**Comment by trampgeek** [comment]
Fixed some time back, so closing.
