### ISSUE TITLE
Problem to make it work

### ISSUE THREAD

**Issue by feerposser** [trampgeek/moodle-filter_ace_inline#23]
Hey, everyone!

Me and my team are trying to execute this filter on our Moodle, but we're having some troubles. We follow the instructions on the [Moodle filter page](https://coderunner.org.nz/mod/page/view.php?id=545) and the instructions here in the repository, but still getting highligth only and any code execution. 

We already use Code Runner installed the filter and try running some available examples and nothing happens.

Those are the steps we already did:

1. Using Moodle 4.1
2. Code Runner 5.1.1 (running on University of Canterbury's Jobe server)
3. We used Atto editor with HTML editor, but already try using TinyMCE with 'code sample' option
4. Try it using ``` markdown and HTML in both editors above
5. Enable sandbox (jobesandbox, ideonesandbox and sendbox web service)

I'm using some codes and examples provided by the Moodle filter page:

`<pre data-ace-interactive-code="">print("Hello squares")
for i in range(10):
    print(i, i ** 2)
</pre>`

`<pre class="language-python" data-ace-interactive-code >
<code>
    def hello():
        print("Hello world!")
    hello()
</code>
</pre>`

And this is the result:
![image](https://user-images.githubusercontent.com/14969618/235751380-45607c20-99b9-4dc7-aa5c-07589d64db6e.png)

The highlight filter works properly, but the "try it" buttom for code execution do not shows up.

Can someone help me figure out what's wrong to run the code?

**Comment by trampgeek** [comment]
The syntax colouring in those images isn't done by Ace. It looks like you have another code highlighting plugin installed, probably _prism._ 

Firstly, though, check that the Ace inline filter is showing up in the filter setting for your course. If not, a sysadmin will need to enable it. If it is there, make sure it's turned on for your course.

If it is already there and turned on, but the other filter is winning the battle to do the colouring, you'll have to find a way to disable the existing filter.

**Comment by feerposser** [comment]
> The syntax colouring in those images isn't done by Ace. It looks like you have another code highlighting plugin installed, probably _prism._
> 
> Firstly, though, check that the Ace inline filter is showing up in the filter setting for your course. If not, a sysadmin will need to enable it. If it is there, make sure it's turned on for your course.
> 
> If it is already there and turned on, but the other filter is winning the battle to do the colouring, you'll have to find a way to disable the existing filter.

I'm going to check those possibilities with my sysadmin team member. 

Thanks for your helping!

**Comment by feerposser** [comment]
My team member disabled the Sintax Highlight filter and the ACE start to working! I can't belive that was suck a simple thing and we don't get it 😅

Thanks for your help!
