### ISSUE TITLE
Can't make it work

### ISSUE THREAD

**Issue by pietrocascio** [trampgeek/moodle-filter_ace_inline#25]
Hopefully I can get some help because I'm unable to make the filter working 🤔

I've tried on my testing Moodle instance and it is not working, in the doubt that it could confict with the theme or any other plugin, I tried in a fresh Moodle instance with the same result.

**Moodle version**: 4.1.1+ (Build: 20230210)
**CodeRunner version**: 5.1.1
**Ace Inline version**: 0.8.3

## CodeRunner Configuration
![image](https://github.com/trampgeek/moodle-filter_ace_inline/assets/886356/36f6e9ec-21c4-4619-bef5-e78558863695)

![image](https://github.com/trampgeek/moodle-filter_ace_inline/assets/886356/8de2fbec-620b-4972-99ea-48c5b92c6212)

## Manage filters section
![image](https://github.com/trampgeek/moodle-filter_ace_inline/assets/886356/44af4b70-5fbc-488d-8180-88322565be51)

## Use case
In my test course I created a page and added the following snippet of code into it:
![image](https://github.com/trampgeek/moodle-filter_ace_inline/assets/886356/5c0827d9-ab53-4027-ac73-946bddfe3290)

The filters configuration for the page are the following:
![image](https://github.com/trampgeek/moodle-filter_ace_inline/assets/886356/f682bbcb-9839-41ed-8c6d-669e21ba2084)

Here what gets rendered:
![image](https://github.com/trampgeek/moodle-filter_ace_inline/assets/886356/53075e45-d3ff-45f8-a326-17016199aeda)

Any idea what I'm doing wrong? I'd love to be able to use this filter.

**Comment by trampgeek** [comment]
Thanks for presenting all the context so clearly.

You say your version of the Ace-in-line filter is 0.8.3. That seems very odd - the current version is 1.3.3 and the version in the Moodle plugin repository is 1.3.1. Where did you you install it from?

The old version will probably work, but it doesn't recognise the newer syntax you're using (specifically, the data-ace-interactive-code property). The old version would require:

    <h4>Testing Ace-inline-filter<h4>
    <pre class="ace-interactive-code">
    def hello():
        print("Hello world!")
    hello()
    </pre>

[Edit: this syntax also works with the latest versions, BTW.]

But I'd recommend you update to the latest version.

**Comment by pietrocascio** [comment]
First of all, thanks a lot for the immediate response.

My bad for the old version but I assumed the one on the GitHub repo was the latest and I got it from there
![image](https://github.com/trampgeek/moodle-filter_ace_inline/assets/886356/c4bff777-759b-48d8-9619-1d90d13e7970)

thanks for pointing that out.

With the latest version, the syntax highlighting is actually working fine as well as the interactive mode.

Thanks again 🙂
