### ISSUE TITLE
Filter Setting Reverts to "Off but available" Instead of Staying "On"

### ISSUE THREAD

**Issue by nmarafo** [trampgeek/moodle-filter_ace_inline#26]
Hello,

In Moodle 4.1 I'm experiencing an issue with the moodle-filter_ace_inline filter. In Site Administration > Plugins > Filters > Manage filters, when I attempt to set the filter to the "On" option, it doesn't retain this setting. After saving, it automatically reverts back to the "Off but available" status.

This behavior prevents me from keeping the filter globally enabled across the Moodle site. I expect the setting to remain "On" after I select it and save, but it consistently switches back to "Off but available".

Could you please investigate this behavior and provide a solution or workaround?

Thank you for your assistance.

**Comment by trampgeek** [comment]
Thanks for reporting. This is indeed a bug. However, for your information: if you change the setting to _On_ in the site administration setting, the change _does_ actually take effect, so the filter is now globally available. The problem occurs when you reload the manage filters page: at that point, the setting gets changed back to _Off, but available_. 

We'll fix in the next release.

**Comment by trampgeek** [comment]
Fix pushed.
