### ISSUE TITLE
Fatal process OOM in CodeRange setup: allocate virtual memory

### ISSUE THREAD

**Issue by feerposser** [trampgeek/moodle-filter_ace_inline#27]
Hello, everyone!

I'm getting an error (print below) when trying to run JavaScript code. Everything is ok when I try to run Python, but running JS look like there is no memory available. Also, everything is ok when I run JS in "normal Code Runner". 

Is this happening because Ace Inline uses sandbox and something need to be setup?

![image](https://github.com/trampgeek/moodle-filter_ace_inline/assets/14969618/3fa0045a-1383-4137-aa23-a73b721910df)

**Comment by trampgeek** [comment]
Thanks for reporting. Yes, it looks like the default amount of memory allocated for a NodeJS task on the Jobe server is no longer sufficient. I'll raise it on the next push to Jobe. 

In the meantime, you can explicitly raise the memory limit within the AceInline code as follows:

    <pre class="ace-interactive-code" lang="nodejs" data-params='{"memorylimit":500}'>
    console.log("Hello world");
    </pre>

That gives the task 500 MB, up from the inadequate default of 200 MB.

**Comment by feerposser** [comment]
Thanks a lot @trampgeek
