### ISSUE TITLE
Problem with function mapping

### ISSUE THREAD

**Issue by lassikor** [trampgeek/moodle-filter_ace_inline#29]
Dear Developers,
I was trying an interactive example for function plotting on page [https://coderunner.org.nz/mod/page/view.php?id=545](https://coderunner.org.nz/mod/page/view.php?id=545) but an error "Mapped function was not found on page" occurs. (See picture below).
![image](https://github.com/trampgeek/moodle-filter_ace_inline/assets/42375494/8d44355f-7944-4364-8db9-d65afa42022a)

The same error occurs in our Moodle installation as well. How can I fix this issue or is there a real issue with the filter?
BR
Lassi Korhonen

**Comment by trampgeek** [comment]
Ah, thanks for drawing my attention to that. The definition of the matplotlibwrapper function has indeed been stripped from the page. I suspect I made the mistake of editing that page with the new TinyMCE editor, which strips script elements :-(

It's reinstated now. Let me know if you have further problems with it.

Thanks again for reporting.

**Comment by lassikor** [comment]
Thank you for a very quick fix! It seems that the function "doubler" is missing on the page as well.
BR
Lassi K.

**Comment by trampgeek** [comment]
Oops, thanks. Fixed now, too.
