### ISSUE TITLE
Do we want to handel <br> tags

### ISSUE THREAD

**Issue by ghost** [trampgeek/moodle-filter_ace_inline#3]
Current behavior
``` html
<pre class="ace-highlight-code">person = ('Angus', 'McGurk', 33)
point = (10, 20)    <br>x_coord, y_coord = point			# Again, parallel assignment to extract coords
print(x_coord, y_coord)</pre>
```

will produce:

```python
person = ('Angus', 'McGurk', 33)
point = (10, 20)    x_coord, y_coord = point			# Again, parallel assignment to extract coords
print(x_coord, y_coord)
 ```

as the br tag is not processed.

Clearly it is better to enter the newline character, but editing the html via a atto editor will use a <br> tag.

I feel that this direct editing without resorting to editing the source html directly should be supported for following reasons:
- constancy with normal <pre> environment
- ease of conversion to use the plugin (this is how I discovered the issue)
- allowing quick edits without resorting to bare html

I was wondering if this was a feeling shared, and thus something that we would like implemented.

Note I am happy to make the required changes.

**Comment by fastsandslash** [comment]
Editing via HTML in Atto Editor no longer adds a <br> tag in the code.
Also, if needing to add a new line, can be added in Atto Editor without tag dysfunction by executing "shift+enter".

As Atto is being phased out, additional TinyMCE support is being phased in to be consistent with Code Samples.
