### ISSUE TITLE
Latest update won't install?

### ISSUE THREAD

**Issue by Richardvi** [trampgeek/moodle-filter_ace_inline#30]
When we go in Moodle to the 'plugins overview' page, we see the update available:

![image](https://github.com/trampgeek/moodle-filter_ace_inline/assets/5486910/1942d7c7-ac2e-49b2-894f-966d9500a082)

However, when we try to install the update we immediately go back to the moodle admin notifications page. 

So the install doesn't work for some reason. I see no error. I have just updated 13 different plugins, but this update is the only one failing without giving any errors.

**Comment by trampgeek** [comment]
My first guess is that it's a file permissions or ownership problem. Can you check the file permissions in the directory subtree <moodlehome>/filter/ace_inline, please? They need to be writeable by the webserver for the update to work through the web interface (which isn't actually possible if you follow the strict security guidelines [here](https://docs.moodle.org/403/en/Security_recommendations)).

A possible set of ownership and permissions can be set on Debian based systems with the commands:

        chown -R root:www-data <moodlehome>/filter/ace_inline
        chmod -R g+rwX<moodlehome>/filter/ace_inline

However, I recommend instead that you check manually how your other parts of the file-hierarchy are configured and make sure the ace_inline subtree is configured likewise.

**Comment by Richardvi** [comment]
Unfortunately, this is all checked and OK. Like i said in the first post: we upgrade/update regularly plugins from Moodle. We have installed around 100 custom plugins and this is the only one that doesn't work. With no error messages... not even with debugging mode on.

**Comment by trampgeek** [comment]
I was able to reproduce the problem. The date stamp in the zip archive in the github repository conflicted with the date stamp that the Moodle repository had recorded when it first uploaded the zip. My bad: I had tweaked the date manually, not realising it would cause problems later. Fixed now by uploading a new version (v1.3.7).

Thanks for reporting.
